version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: hutieu_resto_db
    environment:
      POSTGRES_DB: hutieu_resto
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: